apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  clusterIP: None
  ports:
    - port: 50051
      name: app
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: docker.io/piyushgarg/test-app
        ports:
        - containerPort: 50051
